# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

#r_github_packages:
#  - r-lib/pkgdown

# ------------------------------------------------------------------------------
# need to update gcc for cpp14
# - Use g++-6 so we definitely have C++14 as the default

# base64 resolves to:
# VER=-6
# CC=gcc$(VER)
# CXX=g++$(VER)

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100
  - mkdir -p ~/.R
  - echo "VkVSPS02CkNDPWdjYyQoVkVSKQpDWFg9ZysrJChWRVIp" | base64 -d > ~/.R/Makevars
  - cat ~/.R/Makevars
# ------------------------------------------------------------------------------

matrix:
  include:
  - r: devel
