# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

#r_github_packages:
#  - r-lib/pkgdown

# ------------------------------------------------------------------------------
# need to update gcc for cpp14
# http://dirk.eddelbuettel.com/blog/2017/06/13/
# - Use g++-6 so we definitely have C++14 as the default
# - Tell R not to try enabling C++14, and to just use the default
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
before_install:
    - echo "** Overriding src/Makevars and removing C++14 on Travis only"
    - sed -i 's|CXX_STD = CXX14||' src/Makevars
    - head src/Makevars
    - export CXX=g++-6 CC=gcc-6;
    - echo $CXX
# ------------------------------------------------------------------------------

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'

#    deploy:
#      provider: script
#      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
#      skip_cleanup: true
  - r: oldrel
  - r: 3.2
  - r: 3.1
