# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

#r_github_packages:
#  - r-lib/pkgdown

# ------------------------------------------------------------------------------
# need to update gcc for cpp14
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
before_install:
    - touch ~/.R/Makevars
    - echo "CXX14 = g++" > ~/.R/Makevars
    - echo "CXX14STD = -std=c++14" > ~/.R/Makevars
# ------------------------------------------------------------------------------

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'

#    deploy:
#      provider: script
#      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
#      skip_cleanup: true
  - r: oldrel
  - r: 3.2
  - r: 3.1
