# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

#r_github_packages:
#  - r-lib/pkgdown

# ------------------------------------------------------------------------------
# need to update gcc for cpp14
# https://stackoverflow.com/questions/39728709/using-an-alternate-compiler-for-travis-ci-r-project-builds
# - Use g++-6 so we definitely have C++14 as the default
# - update-alternatives is required for the R session that builds MY package to use g++-6 (and cpp14)
# - The Makevars is for all of the dependencies to use gcc-6 and g++-6 when building those
# (in theory we only needed the Makevars, but this doesn't seem to be enough, as Dirk pointed out)

# base64 resolves to:
# VER=-6
# CC=gcc$(VER)
# CXX=g++$(VER)

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100
  - mkdir -p ~/.R
  - echo "VkVSPS02CkNDPWdjYyQoVkVSKQpDWFg9ZysrJChWRVIp" | base64 -d > ~/.R/Makevars
  - cat ~/.R/Makevars
  - echo "** Overriding src/Makevars and removing C++14 on Travis only"
  - sed -i 's|CXX_STD = CXX14||' src/Makevars
# ------------------------------------------------------------------------------

matrix:
  include:
  - r: devel
