# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

# ------------------------------------------------------------------------------
# Need to update Travis's really old gcc for use with cpp14
# https://stackoverflow.com/questions/39728709/using-an-alternate-compiler-for-travis-ci-r-project-builds
# 1) Use g++-6 so we definitely have C++14 as the default
# 2) update-alternatives is required for the R session that builds MY package
#    to use g++-6 (and cpp14)
# 3) Then we remove the "request" for CXX14 in src/Makevars and let R just find
#    the default, which is now g++-6 (bc of step 2) which uses cpp14 by default.
# 4) A Makevars used to be used for all of the *dependencies* to use gcc-6 and
#    g++-6 when building those (in theory we only needed this Makevars, but
#    this doesn't seem to be enough when building the actual package of
#    interest, as Dirk pointed out)

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100
  - echo "** Overriding src/Makevars and removing C++14 on Travis only"
  - sed -i 's|CXX_STD = CXX14||' src/Makevars
# ------------------------------------------------------------------------------

r_github_packages:
  - r-lib/pkgdown

 matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'

     deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
  - r: oldrel
  - r: 3.2
  - r: 3.1
